# Generated by Django 5.2.5 on 2025-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('descriptions', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
