# Generated by Django 5.2.5 on 2025-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_served', models.IntegerField(max_length=1000)),
                ('countries_empowered', models.IntegerField(max_length=1000)),
                ('saas_product_built', models.IntegerField(max_length=10000)),
                ('clients_served', models.IntegerField(max_length=10000)),
            ],
            options={
                'verbose_name': 'OutrangeNumber',
                'verbose_name_plural': 'OutrangeNumber',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Company Info', 'verbose_name_plural': 'Company Infos'},
        ),
    ]
