# Generated by Django 5.2.5 on 2025-08-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_outreachnumber_alter_companyinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachnumber',
            name='clients_served',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreachnumber',
            name='countries_empowered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreachnumber',
            name='countries_served',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outreachnumber',
            name='saas_product_built',
            field=models.IntegerField(),
        ),
    ]
